### PR TITLE
Updated the order in side bar and generic asset to send asset

### PR DESCRIPTION
**Pull request by KarishmaBothara**
Screen Shot 2020-03-30 at 12 32 56 PM

### CODE REVIEW

**Comment by holygits** [comment]
I think we missed updating the side bar font awesome icons somewhere?
Would be good to do that here

**Comment by KarishmaBothara** [comment]
> I think we missed updating the side bar font awesome icons somewhere?
> Would be good to do that here

sure.. will see what needs to be done for that.

**Comment by KarishmaBothara** [comment]
> > I think we missed updating the side bar font awesome icons somewhere?
> > Would be good to do that here
> 
> sure.. will see what needs to be done for that.

Screen Shot 2020-03-30 at 2 05 34 PM

**Comment by benxgao** [comment]
LGTM

**Comment by benxgao** [comment]
@KarishmaBothara  Could you share it with design team to have a design review please?

**Comment by KarishmaBothara** [comment]
> @KarishmaBothara Could you share it with design team to have a design review please?

sure...thanks

**Comment by KarishmaBothara** [comment]
> > @KarishmaBothara Could you share it with design team to have a design review please?
> 
> sure...thanks

approved by Lillian..

**Pull request merged**
