### PR TITLE
Update dependencies to cennnznet 1.0.0

### PR DESCRIPTION
**Pull request by benxgao**
Integrated with `cennznet/api.js@1.0.0`, tested in the following check-points:

- [x] Sending tx between Alice and Bob;
- [x] Creating new account;
- [x] Sending rpc call in toolbox (tested on getBlockhash method);

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
I think the dependency of @cennznet/api needs to be introduced in this PR? and we need to remove @cennznet/types?

**Comment by benxgao** [comment]
> I think the dependency of @cennznet/api needs to be introduced in this PR? and we need to remove @cennznet/types?
> Which means the rpc call that we need to check is the newly introduced calls in @cennznet/api for get is cennzx buyPrice/sellPrice?
> @holygits ? need ur help with my understanding on this

Now that we have metadata updated, we could get those rpc.cennz calls from metadata directly?

**Comment by KarishmaBothara** [comment]
> > I think the dependency of @cennznet/api needs to be introduced in this PR? and we need to remove @cennznet/types?
> > Which means the rpc call that we need to check is the newly introduced calls in @cennznet/api for get is cennzx buyPrice/sellPrice?
> > @holygits ? need ur help with my understanding on this
> 
> Now that we have metadata updated, we could get those rpc.cennz calls from metadata directly?

No, I guess we can't get rpc calls in metadata.. and thats the reason we decorated it in our api...

**Comment by benxgao** [comment]
If you go to toolbox and select `rpc` and `methods()`, the methods are listed there, I am not sure if they can be used, or I misunderstood it. @KarishmaBothara 

image

**Comment by KarishmaBothara** [comment]
> If you go to toolbox and select `rpc` and `methods()`, the methods are listed there, I am not sure if they can be used, or I misunderstood it. @KarishmaBothara
> 
> image

Yes, this only shows all the available methods in the rpc.. but it doesn't support, meaning you can't make a call for it...

**Comment by benxgao** [comment]
> > If you go to toolbox and select `rpc` and `methods()`, the methods are listed there, I am not sure if they can be used, or I misunderstood it. @KarishmaBothara
> > image
> 
> Yes, this only shows all the available methods in the rpc.. but it doesn't support, meaning you can't make a call for it...

Ok, I will add api now and give a try. May I wonder how can I test it?

**Comment by KarishmaBothara** [comment]
> > > If you go to toolbox and select `rpc` and `methods()`, the methods are listed there, I am not sure if they can be used, or I misunderstood it. @KarishmaBothara
> > > image
> > 
> > 
> > Yes, this only shows all the available methods in the rpc.. but it doesn't support, meaning you can't make a call for it...
> 
> Ok, I will add api now and give a try. May I wonder how can I test it?

In the toolbox, I guess it should be available under RPC calls,  'Call the selected endpoint' should show cennzx and next to it, the methods..

**Comment by holygits** [comment]
Can make a follow up PR to re-introduce @cennznet/api this is good for now 👍

**Comment by KarishmaBothara** [comment]
> Can make a follow up PR to re-introduce @cennznet/api this is good for now 👍

Cool..lets update the end point, and get this merged..

**Pull request merged**
