### PR TITLE
Remove unit dropdown

### PR DESCRIPTION
**Pull request by benxgao**
Kapture 2020-03-26 at 13 48 02

### CODE REVIEW

**Comment by holygits** [comment]
lgtm visually, can you or @KarishmaBothara confirm it transfer the expected amount correctly? (can try with 16000 or 160001 on dev node and check balance)

**Comment by benxgao** [comment]
> lgtm visually, can you or @KarishmaBothara confirm it transfer the expected amount correctly? (can try with 16000 or 160001 on dev node and check balance)

Yeah sure, will do it now.

**Comment by benxgao** [comment]
Just test it, GA transfering works with 1.0.0-rc2, but may not work with latest cennznet node

**Comment by KarishmaBothara** [comment]
> Just test it, GA transfering works with 1.0.0-rc2, but may not work with latest cennznet node

That seems expected behaviour to me.. as we are not using the types which works with latest.. Once we have api instance in UI, it will work with latest CENNZnet node

**Pull request merged**
